export const ABC_SCHEDULE = [
  { time: "00:00", content: "ABC Late Night", duration: 1, isAd: false },
  { time: "00:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "01:00", content: "ABC World News Now", duration: 2, isAd: false },
  { time: "02:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "03:00", content: "America This Morning", duration: 2, isAd: false },
  { time: "04:55", content: "Local Ad Break", duration: 0.08, isAd: true },
  { time: "05:00", content: "Good Morning America", duration: 2, isAd: false },
  { time: "06:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "07:00", content: "Local Morning News", duration: 2, isAd: false },
  { time: "08:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "09:00", content: "The View", duration: 1, isAd: false },
  { time: "09:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "10:00", content: "GMA3", duration: 1, isAd: false },
  { time: "10:55", content: "Local Ad Break", duration: 0.08, isAd: true },
  { time: "11:00", content: "General Hospital", duration: 1, isAd: false },
  { time: "11:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "12:00", content: "Local News", duration: 1, isAd: false },
  { time: "12:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "13:00", content: "The Talk", duration: 1, isAd: false },
  { time: "13:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "14:00", content: "ABC News Special", duration: 1, isAd: false },
  { time: "14:55", content: "Local Ad Break", duration: 0.08, isAd: true },
  { time: "15:00", content: "World News Tonight", duration: 1, isAd: false },
  { time: "15:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "16:00", content: "Prime Time Special", duration: 2, isAd: false },
  { time: "17:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "18:00", content: "ABC Evening Drama", duration: 2, isAd: false },
  { time: "19:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "20:00", content: "20/20", duration: 2, isAd: false },
  { time: "21:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "22:00", content: "Local News", duration: 1, isAd: false },
  { time: "22:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "23:00", content: "Jimmy Kimmel Live", duration: 1, isAd: false },
];

export const NBC_SCHEDULE = [
  { time: "00:00", content: "Tonight Show", duration: 1, isAd: false },
  { time: "00:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "01:00", content: "Late Night", duration: 2, isAd: false },
  { time: "02:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "03:00", content: "NBC News Now", duration: 2, isAd: false },
  { time: "04:55", content: "Local Ad Break", duration: 0.08, isAd: true },
  { time: "05:00", content: "Early Today", duration: 2, isAd: false },
  { time: "06:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "07:00", content: "Today Show", duration: 3, isAd: false },
  { time: "09:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "10:00", content: "Today with Hoda & Jenna", duration: 1, isAd: false },
  { time: "10:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "11:00", content: "Days of Our Lives", duration: 1, isAd: false },
  { time: "11:55", content: "Local Ad Break", duration: 0.08, isAd: true },
  { time: "12:00", content: "NBC News Daily", duration: 1, isAd: false },
  { time: "12:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "13:00", content: "Dateline NBC", duration: 2, isAd: false },
  { time: "14:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "15:00", content: "Local News", duration: 1, isAd: false },
  { time: "15:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "16:00", content: "NBC Nightly News", duration: 1, isAd: false },
  { time: "16:55", content: "Local Ad Break", duration: 0.08, isAd: true },
  { time: "17:00", content: "Access Hollywood", duration: 1, isAd: false },
  { time: "17:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "18:00", content: "Law & Order", duration: 1, isAd: false },
  { time: "18:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "19:00", content: "Law & Order: SVU", duration: 1, isAd: false },
  { time: "19:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "20:00", content: "Chicago Fire", duration: 1, isAd: false },
  { time: "20:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "21:00", content: "Chicago PD", duration: 1, isAd: false },
  { time: "21:55", content: "Local Ad Break", duration: 0.08, isAd: true },
  { time: "22:00", content: "Local News", duration: 1, isAd: false },
  { time: "22:55", content: "Commercial Break", duration: 0.08, isAd: true },
  { time: "23:00", content: "Tonight Show", duration: 1, isAd: false },
];

